### ISSUE TITLE
Enquiry As a SSOC candidate !

### ISSUE THREAD

**Issue by Giri-Aayush** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#1]
where is the code for the website/App. And the  link provided in the read me file  is not working.How to move forward?

**Comment by rohangupta8756** [comment]
> where is the code for the website/App. And the link provided in the read me file is not working.How to move forward?

Same query !!!

**Comment by ConnectBhawna** [comment]
You guys talking about this link right?
Please read this carefully, it is mentioned that create a fork of this project with your name.
As of now, code is not added will add the code today itself.
Happy journey WAGMI.
![Screenshot from 2022-07-14 08-13-18](https://user-images.githubusercontent.com/81790585/178887074-ea797a24-e28a-4659-84f9-9c9d618f57dd.png)
