### ISSUE TITLE
Designing the Intro Screen(Welcome Screen) of the App. That shows after the onboarding Screen.

### ISSUE THREAD

**Issue by ConnectBhawna** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#12]
Make Screen something like this, 
![Screenshot from 2022-08-07 08-34-16](https://user-images.githubusercontent.com/81790585/183273224-bc3e1b46-bded-4124-9052-b278cd2fc330.png)
but added the color combination only yellow or orange.

**Comment by venkey-dev** [comment]
Assign me this issue

**Comment by venkat-clone** [comment]
I've made intro screen do far. So is this Okay or should I need to add more?

Uploading Screenrecording_20220811_205820.mp4…

**Comment by venkey-dev** [comment]
https://user-images.githubusercontent.com/51732590/184177364-443554ae-b7f6-4484-ad04-84aa7798d9ef.mp4

I've made intro screen do far. So is this Okay or should I need to add more?
