### ISSUE TITLE
Design Common  action bar for whole app. 

### ISSUE THREAD

**Issue by ConnectBhawna** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#14]
- Theme of the color would be yellow,orange and white

**Comment by HawkItzme** [comment]
Hey @Bhawna1203 please assign this issue to me.

**Comment by HawkItzme** [comment]
Hey @Bhawna1203 can you show me any demo that what type of Action bar i have to design?

**Comment by ConnectBhawna** [comment]
You can design any type of action bar that you like but must see that the color of the action bar must be related to orange or red.

**Comment by HawkItzme** [comment]
Hey @Bhawna1203 please tell is this okay?

https://user-images.githubusercontent.com/86477458/185708427-55624f1b-9d16-4acc-b20d-30aa58a6c4d0.mp4

**Comment by ConnectBhawna** [comment]
Looking cool to me instead of muskan joy of giving by nature write only MUSKAN(with good font ) .
Apart from that everything looks cool

**Comment by HawkItzme** [comment]
Sure.

**Comment by HawkItzme** [comment]
Hey @Bhawna1203 , how's that?

https://user-images.githubusercontent.com/86477458/185738182-6b363dcf-938b-49cf-af74-3d5ff35c94d3.mp4

**Comment by ConnectBhawna** [comment]
Looking cool to me, make a PR. I will merge it into the code.
Happy Contributing 
Thanks & Regards
Bhawna

**Comment by HawkItzme** [comment]
Okay
