### ISSUE TITLE
Add Registering via Email in Firebase

### ISSUE THREAD

**Issue by ConnectBhawna** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#16]

**Comment by ConnectBhawna** [comment]
- Save the user details in the Firestore database for further usage.
- For reviewing purposes add the firebase screenshot showing data is stored.
- Add the image of the app it is correctly working.
-  Add Toast to the screen when you are done with signing in or sign up it shows "User is successfully registered".

Then Make PR for review.
WAGMI
Happy Contributing

**Comment by CodeFlyAir** [comment]
Hi, I am interested to work on this issue. Please assign the same to me.

**Comment by CodeFlyAir** [comment]
Which email should I use for the firebase account?

**Comment by CodeFlyAir** [comment]
@Bhawna1203 

> Which email should I use for the firebase account?

**Comment by sanjaysargam** [comment]
Can I contribute???

**Comment by sanjaysargam** [comment]
Please assign me

**Comment by sanjaysargam** [comment]
which user details we have to store in Firebase Database?

**Comment by ConnectBhawna** [comment]
Email and Name

**Comment by sanjaysargam** [comment]
> Email and Name

Okk Thank You

**Comment by sanjaysargam** [comment]
> Email and Name

Then personal details and address???

**Comment by sanjaysargam** [comment]
@Bhawna1203 can u please close this issue as completed
