### ISSUE TITLE
Add Auto Login Feature into the App

### ISSUE THREAD

**Issue by ConnectBhawna** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#17]
Something like if a user is already login then he/she doesn't need to log in again and again. Like happens on Whatsapp Twitter and other platforms.

**Comment by CodeFlyAir** [comment]
I have been assigned the registering user using firebase issue. I can simultaneously add this feature too while working on that. Kindly assign the issue to me.

**Comment by venkey-dev** [comment]
At what screen he should navigated to and what key's need to Store if he is logged in and if he is not what screen he needs to navigate.
I know how to do this.

**Comment by ConnectBhawna** [comment]
Main screen of the App, having navigation drawer and other features.

**Comment by venkey-dev** [comment]
Okay, I do, but we need to set one more time after the firebase integration. Can I also add a splash screen to the app?

**Comment by ConnectBhawna** [comment]
It is already added check and then work on this

**Comment by venkey-dev** [comment]
Okay assign me

**Comment by sanjaysargam** [comment]
Can I contribute?

**Comment by sanjaysargam** [comment]
Please assign me

**Comment by azkaNoreen** [comment]
@venkat-clone HI, I would like to contribute.

**Comment by azkaNoreen** [comment]
@Bhawna1203 I'll do it using the shared preferences option available to store some small data locally and then before the main activity appears I'll check if a user is already login then no need for login again

**Comment by sanjaysargam** [comment]
Please kindly assign me. I want to resolve this issue.
