### ISSUE TITLE
Adding the splash Screen

### ISSUE THREAD

**Issue by ConnectBhawna** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#2]
- Add the beautiful splash screen with animation.
- Please share the working app (photo/ recording) before you make the pull request.
- Happy Hacking WAGMI

**Comment by Sarabyeet** [comment]
I think I can work on adding this

**Comment by ConnectBhawna** [comment]
Cool @Sarabyeet 
Let me know if you are facing any issues. 
#WAGMI

**Comment by Sarabyeet** [comment]
Cool, do you have any logo in mind for the splash screen or do I just place a dummy icon there?

**Comment by Sarabyeet** [comment]
@Bhawna1203 Hey I opened a PR, please let me know if it looks good.

**Comment by Sarabyeet** [comment]
You should close this issue now :)
