### ISSUE TITLE
Add two different account 

### ISSUE THREAD

**Issue by ConnectBhawna** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#26]
- One for Admin and another one for People who log in.
- Share the screen recording of the app after adding it so that I am able to figure out that the app is running correctly.

**Comment by HawkItzme** [comment]
I would like to contribute to it, please assign @Bhawna1203

**Comment by Aditya1713** [comment]
Please Assign me this issue @Bhawna1203

**Comment by HawkItzme** [comment]
I asked it first @Bhawna1203  :'(

**Comment by Aditya1713** [comment]
> 

everyone is here to contribute bro let all have some opportunity :)✌

**Comment by ConnectBhawna** [comment]
Yes @HawkItzme , but you already done some contributions to the project(also merged Pr). So I feel to give this opportunity to @Aditya1713 
@HawkItzme do not get sad, Try to work on some other issues. I will add 4-5 new issues today itself.
