### ISSUE TITLE
adding code of conduct file

### ISSUE THREAD

**Issue by anamikarawat2305** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#29]
Every HacktoberFest-2022 participating repository needs a code_of_conduct.md file
So I have created a well curated for this repository.
If everything looks good, you can merge it and add hacktoberfest-accepted label to it.

**Comment by ConnectBhawna** [comment]
Cool Make a PR,I will merge it into the code
Thanks & Happy Hacking
