### ISSUE TITLE
Write Documentation for New User for Setup the Project on their own system

### ISSUE THREAD

**Issue by ConnectBhawna** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#3]

**Comment by ghost** [comment]
Hey @Bhawna1203 assign this issue to me.

**Comment by ConnectBhawna** [comment]
Best of Luck with your first PR.
In case of any doubt, you can reach out to me here.
Happy Coding WAGMI

**Comment by sourabhkumar47** [comment]
Hey, @Bhawna1203 assign me this issue.

**Comment by sourabhkumar47** [comment]
@Bhawna1203 Hey I opened PR #20, please let me know if it looks good.
