### ISSUE TITLE
Add content into the Onboarding screens of App

### ISSUE THREAD

**Issue by ConnectBhawna** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#31]

**Comment by rahul-s-bhatt** [comment]
Hi, I would love to contribute to this project, can I get more details on what content needs to be added on onboarding screens?

**Comment by ConnectBhawna** [comment]
You can add content according to your wish but remember the content should related to the App
Thanks & Regards
Bhawna

**Comment by maityamit** [comment]
@Bhawna1203 Can you assign me?
I would like to contribute to this.

**Comment by ConnectBhawna** [comment]
Sure go ahead
