### ISSUE TITLE
Working on adding Email based authentication in App 

### ISSUE THREAD

**Issue by ConnectBhawna** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#34]
- Use firebase for the same
- Before making the PR share the Firebase console that your email is saved there.
- Thanks & Happy hacking

**Comment by sanjaysargam** [comment]
Can I contribute?

**Comment by ConnectBhawna** [comment]
Sure why not.Start working on the issue

**Comment by sanjaysargam** [comment]
> Sure why not.Start working on the issue
Plz assign me?

**Comment by sanjaysargam** [comment]
> Sure why not.Start working on the issue

I just have to work on signinActivity not on the RegisterActivity right??

**Comment by ConnectBhawna** [comment]
correct

**Comment by sanjaysargam** [comment]
> correct

![FirebaseAuthentication](https://user-images.githubusercontent.com/65113071/194271084-9151158f-2268-4d08-9f68-a53e2e379da5.png)
This is the Firebase Email-Password Authentication

email:- muskan@gmail.com
password:-123456
