### ISSUE TITLE
Add Google Sign in Option in App

### ISSUE THREAD

**Issue by sanjaysargam** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#41]
Implement Google Sign in option using Firebase. 
It's really easy for the users to sign in.

**Comment by sanjaysargam** [comment]
Can I work on this issue??

**Comment by SanjaySargam** [comment]
I starred this repo. Plz kindly add hacktoberfest label and assign me

**Comment by sanjaysargam** [comment]
I starred this repo. Plz kindly add hacktoberfest label and assign me

**Comment by ConnectBhawna** [comment]
@SanjaySargam you can work on it

**Comment by sanjaysargam** [comment]
> @SanjaySargam you can work on it

Okk. Btw Thanks a lot @Bhawna1203 because of u only I have successfully completed hacktoberfest 😊😊
