### ISSUE TITLE
Designing the onBoarding screen of the App.

### ISSUE THREAD

**Issue by ConnectBhawna** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#6]
## Color Combination is yellow shades and orange
- The first screen contains the first feature in the text view as shown "Able to Distribute food to the people who really want"
- The second screen contains the second feature in the text view. and so on.
- Happy Coding
![Screenshot from 2022-08-07 08-04-56](https://user-images.githubusercontent.com/81790585/183272672-a8b8c840-b455-45f6-955a-13baa18d26ce.png)

**Comment by Sarabyeet** [comment]
I think I can take on this, do you want me to make similar design?

**Comment by ConnectBhawna** [comment]
Yups we need to make the design something like just make the theme of the app yellow ,white or orange

**Comment by venkey-dev** [comment]
Assign me this Issue.

**Comment by ConnectBhawna** [comment]
Hey, @venkat-clone are you working on this issue?

**Comment by venkey-dev** [comment]
NO Bhawana if you Assign me I will work on this issue. I have already made these types of screens earlier in my projects.

**Comment by venkat-clone** [comment]
NO Bhawana if you Assign me I will work on this issue.

**Comment by venkat-clone** [comment]
NO Bhawana if you Assign me I will work on this issue.

**Comment by aritra-tech** [comment]
@Bhawna1203 Can you assign me?
I would like to contribute to this.
