### ISSUE TITLE
Design sign in and sign up screen 

### ISSUE THREAD

**Issue by CodeFlyAir** [Bhawna1203/Muskan--The-joy-of-giving-by-nature#7]
Hi, I want to contribute to introducing the Sign in and Sign up Feature using Google Firebase. Kindly assign the issue to me.

**Comment by ConnectBhawna** [comment]
Kindly Make the screen like this with the 
![Screenshot from 2022-08-07 08-20-26](https://user-images.githubusercontent.com/81790585/183272871-8d17a1dd-2408-4034-9794-0901e146a379.png)
same color combination

**Comment by CodeFlyAir** [comment]
Yeah Sure... Can you provide me with the **logo** and what extra **user details** are required during registration?

**Comment by CodeFlyAir** [comment]
Hi,
I was working on a login screen design like this :

![Screenshot 2022-08-07 144449](https://user-images.githubusercontent.com/95049059/183283990-95f25aa6-4efd-467f-ba8b-70d84c42906a.jpg)


Will this work or do I need to change it to the one you attached?

**Comment by ConnectBhawna** [comment]
Works looking cool @CodeFlyAir

**Comment by CodeFlyAir** [comment]
Thanks. Then continuing with this only

**Comment by CodeFlyAir** [comment]
Hello,
I have completed designing the Sign In and Register Screen. Here are the screenshots 👇👇👇

![Muskan(Login   Register UI) - Screenshots](https://user-images.githubusercontent.com/95049059/183305245-ca99157f-7488-46c6-96c3-2e68ce6052a5.jpg)

Let me know if this is good to go and if any improvement is required  :-))

**Comment by ConnectBhawna** [comment]
Looking Great make a PR. I will merge it into the code.
Thanks for Contributing

**Comment by CodeFlyAir** [comment]
Hey I'm getting conflicts due to previous merges in the repo. I need some help with the PR as I am new to this git stuff. Can you plz help me out?

**Comment by CodeFlyAir** [comment]
PR created
